<?php
$thetint = strtolower($thetint);
if($thetint=='aliceblue') { $thetint = 'f0f8ff'; }
if($thetint=='antiquewhite') { $thetint = 'faebd7'; }
if($thetint=='aqua') { $thetint = '00ffff'; }
if($thetint=='aquamarine') { $thetint = '7fffd4'; }
if($thetint=='azure') { $thetint = 'f0ffff'; }
if($thetint=='beige') { $thetint = 'f5f5dc'; }
if($thetint=='bisque') { $thetint = 'ffe4c4'; }
if($thetint=='black') { $thetint = '000000'; }
if($thetint=='blanchedalmond') { $thetint = 'ffebcd'; }
if($thetint=='blue') { $thetint = '0000ff'; }
if($thetint=='blueviolet') { $thetint = '8a2be2'; }
if($thetint=='brown') { $thetint = 'a52a2a'; }
if($thetint=='burlywood') { $thetint = 'deb887'; }
if($thetint=='cadetblue') { $thetint = '5f9ea0'; }
if($thetint=='chartreuse') { $thetint = '7fff00'; }
if($thetint=='chocolate') { $thetint = 'd2691e'; }
if($thetint=='coral') { $thetint = 'ff7f50'; }
if($thetint=='cornflowerblue') { $thetint = '6495ed'; }
if($thetint=='cornsilk') { $thetint = 'fff8dc'; }
if($thetint=='crimson') { $thetint = 'dc143c'; }
if($thetint=='cyan') { $thetint = '00ffff'; }
if($thetint=='darkblue') { $thetint = '00008b'; }
if($thetint=='darkcyan') { $thetint = '008b8b'; }
if($thetint=='darkgoldenrod') { $thetint = 'b8860b'; }
if($thetint=='darkgray') { $thetint = 'a9a9a9'; }
if($thetint=='darkgrey') { $thetint = 'a9a9a9'; }
if($thetint=='darkgreen') { $thetint = '006400'; }
if($thetint=='darkkhaki') { $thetint = 'bdb76b'; }
if($thetint=='darkmagenta') { $thetint = '8b008b'; }
if($thetint=='darkolivegreen') { $thetint = '556b2f'; }
if($thetint=='darkorange') { $thetint = 'ff8c00'; }
if($thetint=='darkorchid') { $thetint = '9932cc'; }
if($thetint=='darkred') { $thetint = '8b0000'; }
if($thetint=='darksalmon') { $thetint = 'e9967a'; }
if($thetint=='darkseagreen') { $thetint = '8fbc8f'; }
if($thetint=='darkslateblue') { $thetint = '483d8b'; }
if($thetint=='darkslategray') { $thetint = '2f4f4f'; }
if($thetint=='darkslategrey') { $thetint = '2f4f4f'; }
if($thetint=='darkturquoise') { $thetint = '00ced1'; }
if($thetint=='darkviolet') { $thetint = '9400d3'; }
if($thetint=='deeppink') { $thetint = 'ff1493'; }
if($thetint=='deepskyblue') { $thetint = '00bfff'; }
if($thetint=='dimgray') { $thetint = '696969'; }
if($thetint=='dimgrey') { $thetint = '696969'; }
if($thetint=='dodgerblue') { $thetint = '1e90ff'; }
if($thetint=='firebrick') { $thetint = 'b22222'; }
if($thetint=='floralwhite') { $thetint = 'fffaf0'; }
if($thetint=='forestgreen') { $thetint = '228b22'; }
if($thetint=='fuchsia') { $thetint = 'ff00ff'; }
if($thetint=='gainsboro') { $thetint = 'dcdcdc'; }
if($thetint=='ghostwhite') { $thetint = 'f8f8ff'; }
if($thetint=='gold') { $thetint = 'ffd700'; }
if($thetint=='goldenrod') { $thetint = 'daa520'; }
if($thetint=='gray') { $thetint = '808080'; }
if($thetint=='grey') { $thetint = '808080'; }
if($thetint=='green') { $thetint = '008000'; }
if($thetint=='greenyellow') { $thetint = 'adff2f'; }
if($thetint=='honeydew') { $thetint = 'f0fff0'; }
if($thetint=='hotpink') { $thetint = 'ff69b4'; }
if($thetint=='indianred') { $thetint = 'cd5c5c'; }
if($thetint=='indigo') { $thetint = '4b0082'; }
if($thetint=='ivory') { $thetint = 'fffff0'; }
if($thetint=='khaki') { $thetint = 'f0e68c'; }
if($thetint=='lavender') { $thetint = 'e6e6fa'; }
if($thetint=='lavenderblush') { $thetint = 'fff0f5'; }
if($thetint=='lawngreen') { $thetint = '7cfc00'; }
if($thetint=='lemonchiffon') { $thetint = 'fffacd'; }
if($thetint=='lightblue') { $thetint = 'add8e6'; }
if($thetint=='lightcoral') { $thetint = 'f08080'; }
if($thetint=='lightcyan') { $thetint = 'e0ffff'; }
if($thetint=='lightgoldenrodyellow') { $thetint = 'fafad2'; }
if($thetint=='lightgray') { $thetint = 'd3d3d3'; }
if($thetint=='lightgrey') { $thetint = 'd3d3d3'; }
if($thetint=='lightgreen') { $thetint = '90ee90'; }
if($thetint=='lightpink') { $thetint = 'ffb6c1'; }
if($thetint=='lightsalmon') { $thetint = 'ffa07a'; }
if($thetint=='lightseagreen') { $thetint = '20b2aa'; }
if($thetint=='lightskyblue') { $thetint = '87cefa'; }
if($thetint=='lightslategray') { $thetint = '778899'; }
if($thetint=='lightslategrey') { $thetint = '778899'; }
if($thetint=='lightsteelblue') { $thetint = 'b0c4de'; }
if($thetint=='lightyellow') { $thetint = 'ffffe0'; }
if($thetint=='lime') { $thetint = '00ff00'; }
if($thetint=='limegreen') { $thetint = '32cd32'; }
if($thetint=='linen') { $thetint = 'faf0e6'; }
if($thetint=='magenta') { $thetint = 'ff00ff'; }
if($thetint=='maroon') { $thetint = '800000'; }
if($thetint=='mediumaquamarine') { $thetint = '66cdaa'; }
if($thetint=='mediumblue') { $thetint = '0000cd'; }
if($thetint=='mediumorchid') { $thetint = 'ba55d3'; }
if($thetint=='mediumpurple') { $thetint = '9370d8'; }
if($thetint=='mediumseagreen') { $thetint = '3cb371'; }
if($thetint=='mediumslateblue') { $thetint = '7b68ee'; }
if($thetint=='mediumspringgreen') { $thetint = '00fa9a'; }
if($thetint=='mediumturquoise') { $thetint = '48d1cc'; }
if($thetint=='mediumvioletred') { $thetint = 'c71585'; }
if($thetint=='midnightblue') { $thetint = '191970'; }
if($thetint=='mintcream') { $thetint = 'f5fffa'; }
if($thetint=='mistyrose') { $thetint = 'ffe4e1'; }
if($thetint=='moccasin') { $thetint = 'ffe4b5'; }
if($thetint=='navajowhite') { $thetint = 'ffdead'; }
if($thetint=='navy') { $thetint = '000080'; }
if($thetint=='oldlace') { $thetint = 'fdf5e6'; }
if($thetint=='olive') { $thetint = '808000'; }
if($thetint=='olivedrab') { $thetint = '6b8e23'; }
if($thetint=='orange') { $thetint = 'ffa500'; }
if($thetint=='orangered') { $thetint = 'ff4500'; }
if($thetint=='orchid') { $thetint = 'da70d6'; }
if($thetint=='palegoldenrod') { $thetint = 'eee8aa'; }
if($thetint=='palegreen') { $thetint = '98fb98'; }
if($thetint=='paleturquoise') { $thetint = 'afeeee'; }
if($thetint=='palevioletred') { $thetint = 'd87093'; }
if($thetint=='papayawhip') { $thetint = 'ffefd5'; }
if($thetint=='peachpuff') { $thetint = 'ffdab9'; }
if($thetint=='peru') { $thetint = 'cd853f'; }
if($thetint=='pink') { $thetint = 'ffc0cb'; }
if($thetint=='plum') { $thetint = 'dda0dd'; }
if($thetint=='powderblue') { $thetint = 'b0e0e6'; }
if($thetint=='purple') { $thetint = '800080'; }
if($thetint=='red') { $thetint = 'ff0000'; }
if($thetint=='rosybrown') { $thetint = 'bc8f8f'; }
if($thetint=='royalblue') { $thetint = '4169e1'; }
if($thetint=='saddlebrown') { $thetint = '8b4513'; }
if($thetint=='salmon') { $thetint = 'fa8072'; }
if($thetint=='sandybrown') { $thetint = 'f4a460'; }
if($thetint=='seagreen') { $thetint = '2e8b57'; }
if($thetint=='seashell') { $thetint = 'fff5ee'; }
if($thetint=='sienna') { $thetint = 'a0522d'; }
if($thetint=='silver') { $thetint = 'c0c0c0'; }
if($thetint=='skyblue') { $thetint = '87ceeb'; }
if($thetint=='slateblue') { $thetint = '6a5acd'; }
if($thetint=='slategray') { $thetint = '708090'; }
if($thetint=='slategrey') { $thetint = '708090'; }
if($thetint=='snow') { $thetint = 'fffafa'; }
if($thetint=='springgreen') { $thetint = '00ff7f'; }
if($thetint=='steelblue') { $thetint = '4682b4'; }
if($thetint=='tan') { $thetint = 'd2b48c'; }
if($thetint=='teal') { $thetint = '008080'; }
if($thetint=='thistle') { $thetint = 'd8bfd8'; }
if($thetint=='tomato') { $thetint = 'ff6347'; }
if($thetint=='turquoise') { $thetint = '40e0d0'; }
if($thetint=='violet') { $thetint = 'ee82ee'; }
if($thetint=='wheat') { $thetint = 'f5deb3'; }
if($thetint=='white') { $thetint = 'ffffff'; }
if($thetint=='whitesmoke') { $thetint = 'f5f5f5'; }
if($thetint=='yellow') { $thetint = 'ffff00'; }
if($thetint=='yellowgreen') { $thetint = '9acd32'; }
?>